const batmanCategorie = {
  page: 1,
  total_results: 115,
  total_pages: 6,
  results: [
    {
      popularity: 46.071,
      vote_count: 13443,
      video: false,
      poster_path: "/dr6x4GyyegBWtinPBzipY02J2lV.jpg",
      id: 272,
      adult: false,
      backdrop_path: "/9myrRcegWGGp24mpVfkD4zhUfhi.jpg",
      original_language: "en",
      original_title: "Batman Begins",
      genre_ids: [28, 80, 18],
      title: "Batman Begins",
      vote_average: 7.6,
      overview:
        "Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.",
      release_date: "2005-06-10"
    },
    {
      popularity: 16.033,
      vote_count: 4352,
      video: false,
      poster_path: "/kBf3g9crrADGMc2AMAMlLBgSm2h.jpg",
      id: 268,
      adult: false,
      backdrop_path: "/2blmxp2pr4BhwQr74AdCfwgfMOb.jpg",
      original_language: "en",
      original_title: "Batman",
      genre_ids: [28, 14],
      title: "Batman",
      vote_average: 7.1,
      overview:
        "The Dark Knight of Gotham City begins his war on crime with his first major enemy being the clownishly homicidal Joker, who has seized control of Gotham's underworld.",
      release_date: "1989-06-23"
    },
    {
      popularity: 21.685,
      vote_count: 2998,
      video: false,
      poster_path: "/79AYCcxw3kSKbhGpx1LiqaCAbwo.jpg",
      id: 415,
      adult: false,
      backdrop_path: "/tgPFZxhDuxWd4VXYaz8eAUznGTF.jpg",
      original_language: "en",
      original_title: "Batman & Robin",
      genre_ids: [28, 35, 14, 878],
      title: "Batman & Robin",
      vote_average: 4.2,
      overview:
        "Along with crime-fighting partner Robin and new recruit Batgirl, Batman battles the dual threat of frosty genius Mr. Freeze and homicidal horticulturalist Poison Ivy. Freeze plans to put Gotham City on ice, while Ivy tries to drive a wedge between the dynamic duo.",
      release_date: "1997-06-20"
    },
    {
      popularity: 16.418,
      vote_count: 212,
      video: false,
      poster_path: "/eiVQORVyVuNNZHPAELuWtlXoQsD.jpg",
      id: 537056,
      adult: false,
      backdrop_path: "/eevJuYAitUe6VwFN29aFwzeyeTr.jpg",
      original_language: "en",
      original_title: "Batman: Hush",
      genre_ids: [28, 16, 80, 9648],
      title: "Batman: Hush",
      vote_average: 6.9,
      overview:
        "A mysterious new villain known only as Hush uses a gallery of villains to destroy Batman's crime-fighting career as well as Bruce Wayne's personal life, which has been further complicated by a  relationship with Selina Kyle/Catwoman.",
      release_date: "2019-07-19"
    },
    {
      popularity: 23.897,
      id: 364,
      video: false,
      vote_count: 3615,
      vote_average: 6.8,
      title: "Batman Returns",
      release_date: "1992-06-19",
      original_language: "en",
      original_title: "Batman Returns",
      genre_ids: [28, 14],
      backdrop_path: "/reQewz6KndV7Js2mfLfaaX8Rj0T.jpg",
      adult: false,
      overview:
        "Having defeated the Joker, Batman now faces the Penguin—a warped and deformed individual who is intent on being accepted into Gotham society, with the help of Max Schreck, a crooked businessman, whom he coerces into helping him run for the position of Mayor of Gotham, while they both attempt to frame Batman in a different light. Batman must attempt to clear his name, all while also deciding just what must be done with the mysterious Catwoman slinking about.",
      poster_path: "/jKBjeXM7iBBV9UkUcOXx3m7FSHY.jpg"
    },
    {
      popularity: 22.222,
      id: 414,
      video: false,
      vote_count: 3093,
      vote_average: 5.3,
      title: "Batman Forever",
      release_date: "1995-06-16",
      original_language: "en",
      original_title: "Batman Forever",
      genre_ids: [28, 80, 14],
      backdrop_path: "/gVTTtYgKIBurNvkGiGC6735b8y.jpg",
      adult: false,
      overview:
        "The Dark Knight of Gotham City confronts a dastardly duo: Two-Face and the Riddler. Formerly District Attorney Harvey Dent, Two-Face believes Batman caused the courtroom accident which left him disfigured on one side. And Edward Nygma, computer-genius and former employee of millionaire Bruce Wayne, is out to get the philanthropist; as The Riddler. Former circus acrobat Dick Grayson, his family killed by Two-Face, becomes Wayne's ward and Batman's new partner Robin.",
      poster_path: "/eTMrHEhlFPHNxpqGwpGGTdAa0xV.jpg"
    },
    {
      popularity: 13.559,
      vote_count: 411,
      video: false,
      poster_path: "/udDVJXtAFsQ8DimrXkVFqy4DGEQ.jpg",
      id: 2661,
      adult: false,
      backdrop_path: "/5gcdof2PKH1emllBdN1VXU706IP.jpg",
      original_language: "en",
      original_title: "Batman",
      genre_ids: [12, 35, 80, 878, 10751],
      title: "Batman",
      vote_average: 6.2,
      overview:
        "The Dynamic Duo faces four super-villains who plan to hold the world for ransom with the help of a secret invention that instantly dehydrates people.",
      release_date: "1966-07-30"
    },
    {
      popularity: 12.496,
      vote_count: 478,
      video: false,
      poster_path: "/bI1YVuhBN6Vws1GP9Mf01DyhC2s.jpg",
      id: 69735,
      adult: false,
      backdrop_path: "/hAhMOPPPxzCKsCu5rUMYdwS8Yb5.jpg",
      original_language: "en",
      original_title: "Batman: Year One",
      genre_ids: [28, 12, 16, 80, 9648],
      title: "Batman: Year One",
      vote_average: 7.2,
      overview:
        "Two men come to Gotham City: Bruce Wayne after years abroad feeding his lifelong obsession for justice and Jim Gordon after being too honest a cop with the wrong people elsewhere. After learning painful lessons about the city's corruption on its streets and police department respectively, this pair learn how to fight back their own way. With that, Gotham's evildoers from top to bottom are terrorized by the mysterious Batman and the equally heroic Gordon is assigned to catch him by comrades who both hate and fear him themselves. In the ensuing manhunt, both find much in common as the seeds of an unexpected friendship are laid with additional friends and rivals helping to start the legend.",
      release_date: "2011-09-27"
    },
    {
      popularity: 17.595,
      vote_count: 3161,
      video: false,
      poster_path: "/1pHOqpdCYNmtRVJs6pGKQKttrPm.jpg",
      id: 324849,
      adult: false,
      backdrop_path: "/jqnbac3oind5VOcAN0mTXyapOGh.jpg",
      original_language: "en",
      original_title: "The Lego Batman Movie",
      genre_ids: [28, 16, 35, 14, 10751],
      title: "The Lego Batman Movie",
      vote_average: 7.2,
      overview:
        'In the irreverent spirit of fun that made "The Lego Movie" a worldwide phenomenon, the self-described leading man of that ensemble—Lego Batman—stars in his own big-screen adventure. But there are big changes brewing in Gotham, and if he wants to save the city from The Joker’s hostile takeover, Batman may have to drop the lone vigilante thing, try to work with others and maybe, just maybe, learn to lighten up.',
      release_date: "2017-02-08"
    },
    {
      popularity: 32.753,
      vote_count: 12708,
      video: false,
      poster_path: "/cGOPbv9wA5gEejkUN892JrveARt.jpg",
      id: 209112,
      adult: false,
      backdrop_path: "/vsjBeMPZtyB7yNsYY56XYxifaQZ.jpg",
      original_language: "en",
      original_title: "Batman v Superman: Dawn of Justice",
      genre_ids: [28, 12, 14],
      title: "Batman v Superman: Dawn of Justice",
      vote_average: 5.8,
      overview:
        "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.",
      release_date: "2016-03-23"
    },
    {
      popularity: 10.413,
      vote_count: 323,
      video: false,
      poster_path: "/7souLi5zqQCnpZVghaXv0Wowi0y.jpg",
      id: 471474,
      adult: false,
      backdrop_path: "/9ojJB7vZR2uDqXdxOzYaADthEBT.jpg",
      original_language: "en",
      original_title: "Batman: Gotham by Gaslight",
      genre_ids: [28, 16, 878, 53],
      title: "Batman: Gotham by Gaslight",
      vote_average: 6.5,
      overview:
        "In an alternative Victorian Age Gotham City, Batman begins his war on crime while he investigates a new series of murders by Jack the Ripper.",
      release_date: "2018-01-12"
    },
    {
      popularity: 12.451,
      vote_count: 369,
      video: false,
      poster_path: "/UUuwP7PEiOzXWH2mP1QkAkFidI.jpg",
      id: 366924,
      adult: false,
      backdrop_path: "/prdrusiPbYES4F5ROISvQRKdTbV.jpg",
      original_language: "en",
      original_title: "Batman: Bad Blood",
      genre_ids: [28, 16, 878],
      title: "Batman: Bad Blood",
      vote_average: 7,
      overview:
        "Bruce Wayne is missing. Alfred covers for him while Nightwing and Robin patrol Gotham City in his stead. And a new player, Batwoman, investigates Batman's disappearance.",
      release_date: "2016-03-22"
    },
    {
      popularity: 10.283,
      id: 321528,
      video: false,
      vote_count: 415,
      vote_average: 6.9,
      title: "Batman vs. Robin",
      release_date: "2015-04-14",
      original_language: "en",
      original_title: "Batman vs. Robin",
      genre_ids: [28, 12, 16],
      backdrop_path: "/oERfMmGc1GJRnC8IuFUH7zpR5z5.jpg",
      adult: false,
      overview:
        'Damian Wayne is having a hard time coping with his father\'s "no killing" rule. Meanwhile, Gotham is going through hell with threats such as the insane Dollmaker, and the secretive Court of Owls.',
      poster_path: "/6g7iQJAgyDn9mep98RXhLI64RcA.jpg"
    },
    {
      popularity: 10.209,
      vote_count: 0,
      video: false,
      poster_path: "/tRe69Ip45keWWR6rBtTtZzfOEoE.jpg",
      id: 414906,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "The Batman",
      genre_ids: [28, 80, 18],
      title: "The Batman",
      vote_average: 0,
      overview:
        "A point-of-view driven noir tale with heavy focus on Batman's detective work. A stand-alone story with no connection to the DCEU.",
      release_date: "2021-06-23"
    },
    {
      popularity: 16.002,
      vote_count: 307,
      video: false,
      poster_path: "/eIAhXROHG8t3QQ7qU0HfZgL5XFf.jpg",
      id: 13851,
      adult: false,
      backdrop_path: "/cAW1NAahXhBUFJZgicBIGPs2OkZ.jpg",
      original_language: "en",
      original_title: "Batman: Gotham Knight",
      genre_ids: [28, 12, 16],
      title: "Batman: Gotham Knight",
      vote_average: 6.6,
      overview:
        "Explore Bruce Wayne's transition from his beginning as a tormented vigilantee to The Dark Knight of a crumbling metropolis with six distinct chapters but intended to be viewed as a whole.",
      release_date: "2008-07-03"
    },
    {
      popularity: 11.989,
      vote_count: 325,
      video: false,
      poster_path: "/gYvSfS6hETW0DmfueJX0eon2VAP.jpg",
      id: 408648,
      adult: false,
      backdrop_path: "/2JVnUtyUKbQm165cXUF9r5iVPDo.jpg",
      original_language: "en",
      original_title: "Batman and Harley Quinn",
      genre_ids: [28, 12, 16, 878],
      title: "Batman and Harley Quinn",
      vote_average: 5.9,
      overview:
        "Batman and Nightwing are forced to team with the Joker's sometimes-girlfriend Harley Quinn to stop a global threat brought about by Poison Ivy and Jason Woodrue, the Floronic Man.",
      release_date: "2017-08-14"
    },
    {
      popularity: 12.752,
      vote_count: 19,
      video: false,
      poster_path: "/rA5bdwbzEAKfvjHRzza6Q3r0otq.jpg",
      id: 602307,
      adult: false,
      backdrop_path: "/sP0ELxnuwPlqq67iQAJaJ7zjJpw.jpg",
      original_language: "en",
      original_title: "Lego DC Batman: Family Matters",
      genre_ids: [16, 10751],
      title: "LEGO DC: Batman - Family Matters",
      vote_average: 5.8,
      overview:
        "In LEGO DC: Batman - Family Matters, suspicion is on high after Batman, Batgirl, Robin and other DC superheroes receive mysterious invitations. However, family values must remain strong when Batman and his team encounter the villainous Red Hood, who is obsessed with destroying the Bat-family and all of Gotham City.",
      release_date: "2019-07-21"
    },
    {
      popularity: 11.661,
      vote_count: 199,
      video: false,
      poster_path: "/eIeT9dsFeKiKNxjWyXHTL92TTrJ.jpg",
      id: 15805,
      adult: false,
      backdrop_path: "/qYir2sJ8j2ZL0sAVPgtnGYyNuvm.jpg",
      original_language: "en",
      original_title: "Batman & Mr. Freeze: SubZero",
      genre_ids: [28, 16, 80, 10751],
      title: "Batman & Mr. Freeze: SubZero",
      vote_average: 6.9,
      overview:
        "When a desperate Mr. Freeze, to save his dying wife, kidnaps Barbara Gordon (Batgirl) as an involuntary organ donor, Batman and Robin must find her before the operation can begin.",
      release_date: "1998-03-17"
    },
    {
      popularity: 15.43,
      vote_count: 842,
      video: false,
      poster_path: "/78kjgspmLLOm2Glgpzqo9cS4GpI.jpg",
      id: 40662,
      adult: false,
      backdrop_path: "/hkguTOGQ4MkjHyd5g4rR6i4MDck.jpg",
      original_language: "en",
      original_title: "Batman: Under the Red Hood",
      genre_ids: [28, 16, 9648],
      title: "Batman: Under the Red Hood",
      vote_average: 7.7,
      overview:
        "Batman faces his ultimate challenge as the mysterious Red Hood takes Gotham City by firestorm. One part vigilante, one part criminal kingpin, Red Hood begins cleaning up Gotham with the efficiency of Batman, but without following the same ethical code.",
      release_date: "2010-07-27"
    },
    {
      popularity: 14.402,
      vote_count: 525,
      video: false,
      poster_path: "/j3SFJqZPeeB9g5JMU7UFLgEqj2T.jpg",
      id: 251519,
      adult: false,
      backdrop_path: "/omK35Mr3oks6bd5efrgsO7CzmLP.jpg",
      original_language: "en",
      original_title: "Son of Batman",
      genre_ids: [28, 12, 16],
      title: "Son of Batman",
      vote_average: 6.8,
      overview:
        "Batman learns that he has a violent, unruly pre-teen son with Talia al Ghul named Damian Wayne who is secretly being raised by Ra's al Ghul and the League of Assassins. When Ra's al Ghul apparently dies after a battle with Deathstroke, Batman must work to stop his long-lost son from taking revenge and guiding him to a righteous path, in addition to the chance for the pair to truly acknowledging each other as family.",
      release_date: "2014-04-20"
    }
  ]
};

const fightclub = {
  adult: false,
  backdrop_path: "/mMZRKb3NVo5ZeSPEIaNW9buLWQ0.jpg",
  belongs_to_collection: null,
  budget: 63000000,
  genres: [{ id: 18, name: "Drama" }],
  homepage: "http://www.foxmovies.com/movies/fight-club",
  id: 550,
  imdb_id: "tt0137523",
  original_language: "en",
  original_title: "Fight Club",
  overview:
    'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
  popularity: 44.815,
  poster_path: "/adw6Lq9FiC9zjYEpOqfq03ituwp.jpg",
  production_companies: [
    {
      id: 508,
      logo_path: "/7PzJdsLGlR7oW4J0J5Xcd0pHGRg.png",
      name: "Regency Enterprises",
      origin_country: "US"
    },
    {
      id: 711,
      logo_path: "/tEiIH5QesdheJmDAqQwvtN60727.png",
      name: "Fox 2000 Pictures",
      origin_country: "US"
    },
    {
      id: 20555,
      logo_path: "/hD8yEGUBlHOcfHYbujp71vD8gZp.png",
      name: "Taurus Film",
      origin_country: "DE"
    },
    {
      id: 54051,
      logo_path: null,
      name: "Atman Entertainment",
      origin_country: ""
    },
    {
      id: 54052,
      logo_path: null,
      name: "Knickerbocker Films",
      origin_country: "US"
    },
    {
      id: 25,
      logo_path: "/qZCc1lty5FzX30aOCVRBLzaVmcp.png",
      name: "20th Century Fox",
      origin_country: "US"
    },
    {
      id: 4700,
      logo_path: "/A32wmjrs9Psf4zw0uaixF0GXfxq.png",
      name: "The Linson Company",
      origin_country: ""
    }
  ],
  production_countries: [
    { iso_3166_1: "DE", name: "Germany" },
    { iso_3166_1: "US", name: "United States of America" }
  ],
  release_date: "1999-10-15",
  revenue: 100853753,
  runtime: 139,
  spoken_languages: [{ iso_639_1: "en", name: "English" }],
  status: "Released",
  tagline: "Mischief. Mayhem. Soap.",
  title: "Fight Club",
  video: false,
  vote_average: 8.4,
  vote_count: 17970
};

const configuration = {
  images: {
    base_url: "http://image.tmdb.org/t/p/",
    secure_base_url: "https://image.tmdb.org/t/p/",
    backdrop_sizes: ["w300", "w780", "w1280", "original"],
    logo_sizes: ["w45", "w92", "w154", "w185", "w300", "w500", "original"],
    poster_sizes: ["w92", "w154", "w185", "w342", "w500", "w780", "original"],
    profile_sizes: ["w45", "w185", "h632", "original"],
    still_sizes: ["w92", "w185", "w300", "original"]
  },
  change_keys: [
    "adult",
    "air_date",
    "also_known_as",
    "alternative_titles",
    "biography",
    "birthday",
    "budget",
    "cast",
    "certifications",
    "character_names",
    "created_by",
    "crew",
    "deathday",
    "episode",
    "episode_number",
    "episode_run_time",
    "freebase_id",
    "freebase_mid",
    "general",
    "genres",
    "guest_stars",
    "homepage",
    "images",
    "imdb_id",
    "languages",
    "name",
    "network",
    "origin_country",
    "original_name",
    "original_title",
    "overview",
    "parts",
    "place_of_birth",
    "plot_keywords",
    "production_code",
    "production_companies",
    "production_countries",
    "releases",
    "revenue",
    "runtime",
    "season",
    "season_number",
    "season_regular",
    "spoken_languages",
    "status",
    "tagline",
    "title",
    "translations",
    "tvdb_id",
    "tvrage_id",
    "type",
    "video",
    "videos"
  ]
};
